#######################################################################################################################
# Represents a box in pixel points where origin (0,0) is the top-left corner of the image
# with positive x-axis pointing to right and positive y-axis pointing down.
#######################################################################################################################

realsense_person/Pixel top_left     #top left point of the box
realsense_person/Pixel bottom_right #bottom right point of the box
