#######################################################################################################################
# The "image" points are pixel points where origin (0,0) is the top-left corner of the image
# with positive x-axis pointing to right and positive y-axis pointing down.
#
# The "world" points are points in meters where the origin (0,0) is the center of the color camera
# with positive x-axis pointing to right, positive y-axis pointing down and positive z-axis pointing forward,
# with respsect to the camera's view.
#######################################################################################################################

realsense_person/Pixel image
geometry_msgs/Point world
