blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/realsenseai/realsense-ros/discussions
    about: For general questions and community discussions
  - name: ROS Wrapper Documentation
    url: https://github.com/realsenseai/realsense-ros/blob/ros2-development/README.md
    about: Browse the ROS Wrapper README
  - name: LibRealSense SDK Issues
    url: https://github.com/realsenseai/librealsense/issues
    about: For issues in the underlying SDK, not the ROS Wrapper
