#######################################################################################################################
# status    0: indicates success.
# status != 0: indicates failure; ignore the "recognition_id"
#######################################################################################################################

int32 tracking_id
---
int32 status
string status_desc
int32 recognition_id

